version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - app-network

  service1:
    build: ./service_1
    expose:
      - "8001"   
    networks:
      - app-network

  service2:
    build: ./service_2
    expose:
      - "8002"   
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

